=head1 NAME

Uttu::Config - Various Uttu configuration settings

=head1 SYNOPSIS

 use Uttu::Config;
  
 print "Default prefix: $Uttu::Config::PREFIX\n"

=head1 DESCRIPTION

This module contains the various configuration settings needed by Uttu.
Currently, only the default installation prefix is stored.

